import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Liam&#39;s Project Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Liam&#39;s Project Site
        </h1>

        <div className={styles.grid}>
          <a href="https://github.com/licrow" className={styles.card}>
            <h2>Github Account &rarr;</h2>
          </a>

          <a href="https://github.com/licrow/nextjs" className={styles.card}>
            <h2>Github Repo &rarr;</h2>
          </a>

          <a
            href="https://www.evangelionunit.one/things"
            className={styles.card}
          >
            <h2>Favourite/Least Favourite Things &rarr;</h2>
          </a>

          <a
            href="https://www.evangelionunit.one/interests"
            className={styles.card}
          >
            <h2>Interests &rarr;</h2>
            <p>
            </p>
          </a>

          <a
            href="https://www.evangelionunit.one/redirect"
            className={styles.card}
          >
            <h2>How to redirect a path? &rarr;</h2>
            <p></p>
          </a>

          <a
            href="https://www.evangelionunit.one/domain"
            className={styles.card}
          >
            <h2>How to add a custom domain? &rarr;</h2>
            <p>
            </p>
          </a>
            
          <a
            href="https://www.evangelionunit.one/thoughts"
            className={styles.card}
          >
            <h2>What are common problems? And thoughts on the test &rarr;</h2>
            <p></p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
