import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
	  <div className={styles.container}>

	<Head>
		<title>Liam&#39;s Project Site</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" /> </Head>
	<main className={styles.main}>
		<h1 className={styles.title}>
          Interests and Learning
        </h1>
		<div>
			<p>4b.<br />I want to develop my skills in understanding both front end and programming languages, especially from a support standpoint. This is a very diverse field but with Vercel’s focus on specific coding areas such as Next.js I think this is something I would be capable of doing.</p>

<p>4c.<br />I’m currently studying American football strategy with recorded classes. I’m a big fan of the sport and it has helped with my enjoyment and understanding of the game immensely, given its relative complexity.</p>
		</div>
	</main>
	<footer className={styles.footer}> <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> </footer>
</div> ) }
